name: CursodjangoCI

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
        cp contrib/env-sample .env

    - name: Lint with flake8
      run: |
        pipenv run flake8 .
        pipenv run pytest --cov=pypro

    - name: Coverage
      env:
        CODECOV_TOKEN: '13c61f04-79eb-4bc6-b3f3-080cc90faa6b'
      run: |
        pipenv run codecov
